services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPOCONSULT\TcHenny\:
    resource: '../Classes/*'

  TYPOCONSULT\TcHenny\Factory\:
    resource: '../Classes/Factory/*'
    public: true